config/routes.rb
Rails.application.routes.draw do
 devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
 }

  devise_scope :customer do
    post 'customer/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    resources :reviews, only: [:index, :create, :update, :destroy]
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get :quit
        patch :out
      end
      member do
        get :list
      end
      resource :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :posts, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
      collection do
        get 'search'
      end
      resources :bookmarks, only: [:index, :create, :destroy]
    end
  end

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "/" => "homes#top"
    # resources :tags, only: [:new, :create, :destroy]
    resources :posts, only: [:show, :edit, :create, :update, :destroy] do
      collection do
        get 'search'
      end
    end
    resources :customers, only: [:index, :show, :edit, :update] do
      member do
        get :list
      end
    end
    resources :reviews, only: [:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  geocoded_by :address
  after_validation :geocode

  belongs_to :customer


  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :reviews
  has_many :bookmarks, dependent: :destroy

  # scope :multiple, -> (multiple_params) do      #scopeでsearchメソッドを定義。(search_params)は引数
  #   return if multiple_params.blank?      #検索フォームに値がなければ以下の手順は行わない

  # end

  validates :store_name, presence: true
  validates :tag_ids, presence: true
  validates :address, presence: true

  def bookmarked_by?(customer)
    bookmarks.where(customer_id: customer).exists?
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_q, only: [:index, :search]
  def show
    @post = Post.find(params[:id])
    @reviews = @post.reviews.page(params[:page]).per(15).order(created_at: :desc)
    @bookmarks_count = @post.bookmarks.count
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to admin_post_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_path
  end

  def search
    if params[:tag_id].present?
      @tag = Tag.find(params[:tag_id])
      @q = @tag.posts.ransack(params[:q])
    else
      @q = Post.ransack(params[:q])
    end
    @results = @q.result.page(params[:page]).per(10).order(created_at: :desc).distinct
  end

  private

  def set_q
    @q = Post.ransack(params[:q])
    @results = @q.result
  end

  def post_params
    params.require(:post).permit(:customer_id, :image, :store_name, :activity_monday,
      :activity_tuesday, :activity_wednesday, :activity_thursday, :activity_friday,
      :activity_saturday, :activity_sunday, :holiday, :business_time, :post_comment,
      :lat, :lng, :address, tag_ids: [])
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_list.html.erb
<h3 class="title">投稿一覧</h3>
<div class="row">
  <%= paginate @posts %>
  <% @posts.each do |post| %>
    <div class="col-md-12 col-sm-12">
      <div class="post_list">
        <table class="post" border="1">
          <tbody>
            <tr>
              <td rowspan="7" width="25%" align="center">
                <%= link_to admin_post_path(post.id) do %>
                  <% if post.image.attached? %>
                    <%= image_tag post.image, size: "140x140" %>
                  <% else %>
                    <%= image_tag asset_path("no_image.jpg"), size: "140x140" %>
                  <% end %>
                <% end %>
              </td>
            </tr>
            <tr>
              <th width="15%">店名</th>
              <td><%= post.store_name %></td>
            </tr>
            <tr>
              <th>営業日</th>
              <td>
                <%  weekly_columns.each_with_index do |day,i| %>
                  <% if post[day] == true %>
                   <a><%= ["月","火","水","木","金","土","日"][i] %></a>
                  <% end %>
                <% end %>
              </td>
            </tr>
            <tr>
              <th>営業時間</th>
              <td><%= post.business_time %></td>
            </tr>
            <tr>
              <th>ジャンル</th>
              <td>
                <!--ジャンル-->
                <% post.tags.each do |tag| %>
                  <%= tag.genre %>
                <% end %>
                <!--ジャンル-->
              </td>
            </tr>
            <tr>
              <th>所在地</th>
              <td><%= post.address %></td>
            </tr>
            <tr>
              <th>評価平均</th>
              <td>
                <% if post.reviews.exists? %>
                  <%= post.reviews.average(:star).floor(1) %>
                <%else%>
                  ー
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
  <%= paginate @posts %>
</div>

app/views/admin/posts/_show.html.erb
<div class="col-md-12 col-sm-12">
  <h4>投稿者：
    <%= link_to admin_customer_path(@post.customer.id) do %>
      <%= @post.customer.name  %>さん
    <% end %>
  </h4>
  <p>
    <%= link_to "編集・削除", edit_admin_post_path(@post.id), class: "btn btn-success" %>
    <%= @bookmarks_count %>件のいいね！
  </p>
</div>
<div class="col-md-7 col-sm-12">
  <div class="post_list">
    <table class="post" border="1">
      <tbody>
        <tr>
          <td rowspan="8" width="25%" align="center">
            <% if @post.image.attached? %>
              <%=link_to @post.image,  "data-lightbox": @post.image do %>
                <%= image_tag @post.image, size: "150x150" %>
              <% end %>
            <% else %>
              <%= image_tag asset_path("no_image.jpg"), size: "150x150" %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>店名</td>
          <td><%= @post.store_name %></td>
        </tr>
        <tr>
          <th>営業日</td>
          <td>
            <%  weekly_columns.each_with_index do |day,i| %>
              <% if @post[day] == true %>
               <a><%= ["月","火","水","木","金","土","日"][i] %></a>
              <% end %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>営業時間</td>
          <td><%= @post.business_time %></td>
        </tr>
        <tr>
          <th>定休日</td>
          <td><%= @post.holiday %></td>
        </tr>
        <tr>
          <th>ジャンル</td>
          <td>
            <% @post.tags.each do |tag| %>
              <%= tag.genre %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>コメント</td>
          <td><%= @post.post_comment %></td>
        </tr>
        <tr>
          <th>所在地</td>
          <td><%= @post.address %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="col-md-5 col-sm-12">
  <div id='map'></div>

  <style>
  #map {
    height: 250px;
    width: 80%;
  }
  </style>

   <!--js部分-->
  <script>
  //初期マップの設定
  let map
  let marker
  function initMap(){
    geocoder = new google.maps.Geocoder()

    map = new google.maps.Map(document.getElementById('map'), {
      center:  {lat: <%= @post.lat %>, lng: <%= @post.lng %>},
      zoom: 15,
    });

     marker = new google.maps.Marker({
      position:  {lat: <%= @post.lat %>, lng: <%= @post.lng %>},
      map: map
    });
  }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap" async defer></script>
</div>

app/views/admin/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-12">
      <h3 class="title">投稿編集画面</h3>
    </div>
    <div class="col-md-6 col-sm-12 post_screen">
      <%= form_with model: @post, url: admin_post_path(@post.id), local: true  do |f| %>
        <table>
          <tr>
            <td><%= f.label "画像" %></td>
            <td><%= f.file_field :image, accept: "image/*" %></td>
          </tr>
          <tr>
            <td><%= f.label "店名" %></td>
            <td><%= f.text_field :store_name %></td>
          </tr>
          <tr>
            <td><%= f.label "営業日" %></td>
            <td>
              <span class="checkbox-inline">
                <% weekly_columns.each_with_index do |day,i| %>
                  <%= f.check_box day.to_sym, {}, "true", "false" %>
                  <%= f.label day.to_sym, ["月", "火", "水", "木", "金", "土", "日"][i] %>
                <% end %>
              </span>
            </td>
          </tr>
          <tr>
            <td><%= f.label "営業時間" %></td>
            <td><%= f.text_field :business_time, placeholder: "11:00~15:30, 17:00~23:30", :size=>"30" %></td>
          </tr>
          <tr>
            <td><%= f.label "定休日" %></td>
            <td><%= f.text_field :holiday, placeholder: "例: 毎週月曜日, 第三月曜日", :size=>"30" %></td>
          </tr>
          <tr>
            <td>
              <%= f.label 'ジャンル' %>
            </td>
            <td>
              <div class="check_box">
                <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :genre) do |tag| %>
                 <div class="tag_check">
                    <%= tag.label do %>
                      <%= tag.check_box %>
                      <%= tag.text %>
                    <% end %>
                  </div>
                 <% end %>
               </div>
            </td>
          </tr>
          <tr>
            <td><%= f.label "コメント" %></td>
            <td><%= f.text_area :post_comment, :size=>"30x5" %></td>
          </tr>
        </table>
      </div>
      <div class="col-md-6 col-sm-12 post_screen">
        <div class="maps">
          <div class="actions">
            <input id="address" type="textbox">
            <input type="button" value="検索" onclick="codeAddress()"><br>
            <%= f.label :address,"店舗所在地" %>
            <%= f.text_field :address %><br>
            <%= f.label :lat,"緯度" %>
            <%= f.text_field :lat, id: :lat %><br>
            <%= f.label :lng,"経度" %>
            <%= f.text_field :lng, id: :lng %>
          </div>
          <p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
          <div id='map'></div>
          <style>
          #map {
            height: 300px;
            width: 300px;
          }
          </style>

          <script>
          //初期マップの設定
          let map
          let marker
          function initMap(){
            geocoder = new google.maps.Geocoder()

            map = new google.maps.Map(document.getElementById('map'), {
              center:  {lat: <%= @post.lat %>, lng:<%= @post.lng %>},  //東京
              zoom: 15,

            });
          }

          //検索後のマップ作成
          let geocoder
          let aft
          function codeAddress(){
            let inputAddress = document.getElementById('address').value;
            geocoder.geocode( { 'address': inputAddress}, function(results, status) {
              if (status == 'OK') {
                  //マーカーが複数できないようにする
                  if (aft == true){
                      marker.setMap(null);
                  }

                  //新しくマーカーを作成する
                  map.setCenter(results[0].geometry.location);
                      marker = new google.maps.Marker({
                      map: map,
                      position: results[0].geometry.location,
                      draggable: true	// ドラッグ可能にする
                  });

                  //二度目以降か判断
                  aft = true

                  //検索した時に緯度経度を入力する
                  document.getElementById('lat').value = results[0].geometry.location.lat();
                  document.getElementById('lng').value = results[0].geometry.location.lng();
                  document.getElementById('post_address').value = document.getElementById('address').value;

                  // マーカーのドロップ（ドラッグ終了）時のイベント
                  google.maps.event.addListener( marker, 'dragend', function(ev){
                      // イベントの引数evの、プロパティ.latLngが緯度経度
                      document.getElementById('lat').value = ev.latLng.lat();
                      document.getElementById('lng').value = ev.latLng.lng();
                  });
              } else {
                alert('該当する結果がありませんでした：' + status);
              }
            });
          }

          </script>
          <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap" async defer></script>
          <div class="submit">
            <%= f.submit "変更する", class: "btn btn-success" %>
            <%= link_to "削除する", admin_post_path(@post.id), method: :delete,
                "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/posts/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 col-sm-12">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        複数項目で絞り込む
      </button>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <%= search_form_for @q, url: search_admin_posts_path do |f| %>
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">複数項目で絞り込む</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <ul>
                <li class="search-nav-content">
                  <p><%= f.label "ジャンル" %></p>
                  <%= f.collection_check_boxes :post_tags_tag_id_in, Tag.all, :id, :genre, {} do |c| %>
                    <%= c.label {c.check_box + c.text} %>
                  <% end %>
                </li>
                <li class="search-nav-content">
                  <p><%= f.label :address_start, "住所" %></p>
                  <%= f.search_field :address_start, placeholder: "東京都" %>
                </li>
              </ul>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit '検索' %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <p>
        <%= form_tag search_admin_posts_path, method: :get, class: "boards_searchForm" do %>
          <%= select_tag :tag_id,
              options_from_collection_for_select(Tag.all, :id, :genre, params[:tag_id]),
              {
                prompt: "ジャンルで絞り込み",
                onchange: 'submit(this.form);'
              }
          %>
        <% end %>
      </p>
    </div>
    <div class="col-md-9 col-sm-12">
      <h3 class="title">投稿一覧</h3>
      <div class="row">
        <%= paginate @results %>
        <% @results.each do |post| %>
          <div class="col-md-12 col-sm-12">
            <div class="post_list">
              <table class="post" border="1">
                <tbody>
                  <tr>
                    <td rowspan="7" width="25%" align="center">
                      <%= link_to admin_post_path(post.id) do %>
                        <% if post.image.attached? %>
                          <%= image_tag post.image, size: "140x140" %>
                        <% else %>
                          <%= image_tag 'no_image', size: "140x140" %>
                        <% end %>
                      <% end %>
                    </td>
                  </tr>
                  <tr>
                    <th width="15%">店名</th>
                    <td><%= post.store_name %></td>
                  </tr>
                  <tr>
                    <th>営業日</th>
                    <td>
                      <%  weekly_columns.each_with_index do |day,i| %>
                        <% if post[day] == true %>
                         <a><%= ["月","火","水","木","金","土","日"][i] %></a>
                        <% end %>
                      <% end %>
                    </td>
                  </tr>
                  <tr>
                    <th>営業時間</th>
                    <td><%= post.business_time %></td>
                  </tr>
                  <tr>
                    <th>ジャンル</th>
                    <td>
                      <!--ジャンル-->
                      <% post.tags.each do |tag| %>
                        <%= tag.genre %>
                      <% end %>
                      <!--ジャンル-->
                    </td>
                  </tr>
                  <tr>
                    <th>所在地</th>
                    <td><%= post.address %></td>
                  </tr>
                  <tr>
                    <th>評価平均</th>
                    <td>
                      <% if post.reviews.exists? %>
                        <%= post.reviews.average(:star).floor(1) %>
                      <%else%>
                        ー
                      <% end %>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        <% end %>
        <%= paginate @results %>
      </div>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row">
    <%= render 'admin/posts/show', posts: @posts %>

    <div class="col-md-12 col-sm-12">
      <div class="review">
        <div class="title">
          <h4>
            口コミ一覧
            <%= link_to "画像一覧", admin_reviews_path(id: @post.id) %>
          </h4>
        </div>
        <%= paginate @reviews %>
        <div class="review_all">
          <% @reviews.each do |r| %>
            <div class="review_box">
              投稿日時:<%= r.created_at.strftime("%Y/%m/%d %H:%M") %>
              <% if r.customer.image.attached? %>
                <%= image_tag r.customer.image, size: "50x50" %>
              <% else %>
                <%= image_tag asset_path("no_image.jpg"), size: "50x50" %>
              <% end %>
              <%= link_to admin_customer_path(r.customer.id) do %>
                <%= r.customer.name %>
              <% end %>

              <%= link_to "削除", admin_review_path(r.id), method: :delete,
                  "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %><br>

              <div id="star_<%= r.id %>"></div>

              <script>
                $('#star_<%= r.id %>').empty();
                // var elem = document.getElementById("star_<%= r.id %>");
                // var opt = {
                //   // size: 36,
                //   starOff: "<%= asset_path('star-off.png') %>",
                //   starOn: "<%= asset_path('star-on.png') %>",
                //   readOnly: true, // 読み知り専用
                //   score: <%= r.star %>, // score
                // };
                raty(document.getElementById("star_<%= r.id %>"), // 表示する場所のid
                  {
                    starOff: "<%= asset_path('star-off.png') %>", // 星OFFの画像パス
                    starOn: "<%= asset_path('star-on.png') %>", // 星ONの画像パス
                    readOnly: true, // 読み知り専用
                    score: <%= r.star %>, // 表示する星の数
                  }
                )
              </script>

              <% if r.images.attached? %>
                <% r.images.each do |image| %>
                  <%=link_to image, "data-lightbox": image do %>
                    <%= image_tag image, size: '80x80' %>
                  <% end %>
                <% end %>
              <% end %>
              <div class="review_comment">
                <%= r.review_comment %>
              </div>
            </div>
          <% end %>
        </div>
        <%= paginate @reviews %>
      </div>
    </div>
  </div>
</div>