config/routes.rb
Rails.application.routes.draw do
 devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
 }

  devise_scope :customer do
    post 'customer/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    resources :reviews, only: [:index, :create, :update, :destroy]
    resources :customers, only: [:show, :edit, :update] do
      collection do
        get :quit
        patch :out
      end
      member do
        get :list
      end
      resource :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :posts, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
      collection do
        get 'search'
      end
      resources :bookmarks, only: [:index, :create, :destroy]
    end
  end

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "/" => "homes#top"
    # resources :tags, only: [:new, :create, :destroy]
    resources :posts, only: [:show, :edit, :create, :update, :destroy] do
      collection do
        get 'search'
      end
    end
    resources :customers, only: [:index, :show, :edit, :update] do
      member do
        get :list
      end
    end
    resources :reviews, only: [:index, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ramen</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">

    <script src="https://kit.fontawesome.com/127dcb1b69.js" crossorigin="anonymous"></script>

    <!--画像のポップアップ(以下三行)-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>

  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <!--<div class="container">-->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
              <li>
                <%= link_to root_path, class: "nav-link text-light" do %>
                  <i class="fa-solid fa-house"></i>
                  HOME
                <% end %>
              </li>
              <li>
                <%= link_to customer_path(current_customer), class: "nav-link text-light" do %>
                  <i class="fa-solid fa-user"></i>
                  MY PAGE
                <% end %>
              </li>
              <li>
                <%= link_to posts_path, class: "nav-link text-light" do  %>
                  <i class="fa-solid fa-list-ul"></i>
                  投稿一覧
                <% end %>
              </li>
              <li>
                <%= link_to destroy_customer_session_path, method: :delete, class: "nav-link text-light" do  %>
                  <i class="fa-sharp fa-solid fa-arrow-right-from-bracket"></i>
                  ログアウト
                <% end %>
              </li>

              <% elsif admin_signed_in? %>
              <li>
                <%= link_to admin_path, class: "nav-link text-light" do %>
                  <i class="fa-solid fa-list-ul"></i>
                  投稿一覧
                <% end %>
              </li>
              <li>
                <%= link_to admin_customers_path, class: "nav-link text-light" do %>
                  <i class="fa-solid fa-users"></i>
                  会員一覧
                <% end %>
              </li>
              <li>
                <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-light" do  %>
                  <i class="fa-sharp fa-solid fa-arrow-right-from-bracket"></i>
                  ログアウト
                <% end %>
              </li>

              <% else %>
              <li>
                <%= link_to root_path, class: "nav-link text-light" do %>
                  <i class="fa-solid fa-house"></i>
                  HOME
                <% end %>
              </li>
              <li>
                <%= link_to new_customer_registration_path, class: "nav-link text-light" do %>
                  <i class="fa-solid fa-user-plus"></i>
                  新規登録
                <% end %>
              </li>
              <li>
                <%= link_to new_customer_session_path, class: "nav-link text-light" do  %>
                  <i class="fa-solid fa-right-to-bracket"></i>
                  ログイン
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        <!--</div>-->
      </header>
      <%= yield %>
      <footer class="footer">
        <p class="text-center">Ramen_kaido</p>
      </footer>
    </body>
</html>